### PR TITLE
add AR 6.0 support

### PR DESCRIPTION
**Pull request by jakedouglas**
This PR expands the compatibility specifier for Rails 6.0.x and adds an appraisal for Rails 6.0.

The version of `sqlite3` specified by Rails changed in this version, so I moved it from the gemspec into the appraisals.

### CODE REVIEW

**Comment by jakedouglas** [comment]
Removing `sqlite3` from the `Gemfile` causes that build to fail, e.g. https://travis-ci.org/ArcadiaPower/fast-versioning/jobs/634843621. Should we just remove `Gemfile` from `.travis.yml`?

**Comment by jakedouglas** [comment]
Also not sure why Travis isn't reporting the status to the PR.

**Comment by iiwo** [comment]
> Removing `sqlite3` from the `Gemfile` causes that build to fail, e.g. https://travis-ci.org/ArcadiaPower/fast-versioning/jobs/634843621. Should we just remove `Gemfile` from `.travis.yml`?

maybe adding `s.add_development_dependency 'sqlite3'` without version restriction would make this pass?

**Comment by jakedouglas** [comment]
> maybe adding `s.add_development_dependency 'sqlite3'` without version restriction would make this pass?

Worked :+1:

**Review by iiwo — APPROVED** [review]
👍 🚢

**Pull request merged**
