### PR TITLE
support AR 6.1 + PT 12.3

### PR DESCRIPTION
**Pull request by jakedouglas**
PT 12 is required for AR 6.1, so I skipped PT 11 🤷‍♂️

### CODE REVIEW

**Comment by iiwo** [comment]
👍

**Review by iiwo — APPROVED** [review]
👍

**Comment by jakedouglas** [comment]
Mind publishing again? I don't think I have access 😄

**Comment by iiwo** [comment]
done https://rubygems.org/gems/fast_versioning/versions/0.7.0

**Pull request merged**
